---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-apiserver-config"
  namespace: "{{ .Release.Namespace }}"
data:
  auth.yaml: |
    # Configuration of auth backend
    ---
    {{- with .Values.authentication.keycloak }}
    oidc:
      url: "{{ .keycloakURL }}"
      client_id: "{{ .clientName }}"
      callback_url: "{{ $.Values.ingress.host }}/#/callback/oidc"
      scopes: [openid, email, profile, roles]
      cacert: /cacert/ca.crt
      display_name: Keycloak
      roles_field: snooze2-roles
      color: '#00a2cf'
      icon: 'Openid'
    {{- end }}
  {{- if .Values.apiserver.cors }}
  cors.yaml: |
    # CORS configuration
    ---
    {{- .Values.apiserver.cors | toYaml | nindent 4 }}
  {{- end }}
