---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-apiserver-config"
  namespace: "{{ .Release.Namespace }}"
data:
  auth.yaml: |
    # Configuration of auth backend
    ---
    {{- .Values.apiserver.auth | toYaml | nindent 6 }}
  {{- if .Values.apiserver.cors }}
  cors.yaml: |
    # CORS configuration
    ---
    {{- .Values.apiserver.cors | toYaml | nindent 4 }}
  {{- end }}
