{{- if eq .Values.apiserver.secretKey.secretName "" }}
---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: "{{ .Release.Name }}-apiserver-secret"
  namespace: "{{ .Release.Namespace }}"
spec:
  fields:
  - encoding: hex
    fieldName: secret_key
    length: "128"
{{- end }}
