---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-apiserver"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: snooze
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: apiserver
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: http
    targetPort: http
    protocol: TCP
    appProtocol: http
  selector:
    app.kubernetes.io/name: snooze
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: apiserver
