---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-api"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: snooze
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    name: rest-api
    targetPort: rest-api
    protocol: TCP
    appProtocol: http
  selector:
    app.kubernetes.io/name: snooze
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: api
