{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    {{- if .Values.ingress.certManager.enabled }}
    cert-manager.io/{{ .Values.ingress.certManager.issuerKind | kebabcase }}: "{{ .Values.ingress.certManager.issuerName }}"
    cert-manager.io/common-name: "{{ .Values.ingress.host }}"
    {{- end }}
spec:
  ingressClassName: "{{ .Values.ingress.className }}"
  rules:
  - host: "{{ required "ingress.host value required" .Values.ingress.host }}"
    http:
      paths:
      - backend:
          service:
            name: "{{ .Release.Name }}-server"
            port:
              number: 5200
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - "{{ .Values.ingress.host }}"
    secretName: "{{ .Release.Name }}-ingress-tls"
{{- end }}

