# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/monitoring.coreos.com/podmonitor_v1.json
{{- if .Values.server.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "{{ .Release.Name }}-server"
  namespace: "{{ .Release.Namespace }}"
  {{- with .Values.server.podMonitor.extraLabels }}
  labels: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podMetricsEndpoints:
  - path: /metrics
    port: http
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: snooze-server
      app.kubernetes.io/instance: "{{ .Release.Name }}"
{{- end }}
