---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-activechecks"
  namespace: "{{ .Release.Namespace }}"
data:
  probes.yaml: |-
    # Active checks configuration
    probes:
    - name: snooze-syslog
      syslog:
        address: snooze-syslog
        port: 514
        format: rfc5424
