{{- if .Values.snmptrap.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-snmptrap"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: snooze-snmptrap
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: snmptrap
    app.kubernetes.io/part-of: "{{ .Release.Name }}"
spec:
  type: LoadBalancer
  ports:
  - port: 162
    protocol: UDP
    targetPort: snmptrap
    name: snmptrap
  selector:
    app.kubernetes.io/name: snooze-snmptrap
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  sessionAffinity: None
{{- end }}
