---
version: v2beta1
name: snooze

vars:
  LOCAL_REPO:
    question: Specify the local repo that will be used
  HTTP_PROXY:
    question: Specify the address of an HTTP_PROXY/HTTPS_PROXY (if needed)
    default: ""
  NO_PROXY:
    question: Specify the NO_PROXY variable (if needed)
    default: ""

# This is a list of `pipelines` that DevSpace can execute (you can define your own)
pipelines:
  # This is the pipeline for the main command: `devspace dev` (or `devspace run-pipeline dev`)
  dev:
    run: |-
      run_dependencies --all       # 1. Deploy any projects this project needs (see "dependencies")
      ensure_pull_secrets --all    # 2. Ensure pull secrets
      start_dev ui                # 4. Start dev mode "app" (see "dev" section)

# This is a list of `images` that DevSpace can build for this project
# We recommend to skip image building during development (devspace dev) as much as possible
images:
  snooze:
    image: ${LOCAL_REPO}/snooze
    dockerfile: ./Dockerfile
  snooze-ui:
    image: ${LOCAL_REPO}/snooze-ui
    dockerfile: ./ui/Dockerfile
  snooze-ui-dev:
    image: ${LOCAL_REPO}

# This is a list of `dev` containers that are based on the containers created by your deployments
dev:
  ui:
    labelSelector:
      app.kubernetes.io/name: snooze
      app.kubernetes.io/component: ui
    devImage: ${LOCAL_REPO}/snooze-ui-dev:develop
    env:
    - name: HTTP_PROXY
      value: ${HTTP_PROXY}
    - name: HTTPS_PROXY
      value: ${HTTP_PROXY}
    - name: NO_PROXY
      value: ${NO_PROXY}
    sync:
    - path: ./ui:/code
      excludePaths:
      - ./ui/node_modules/
      uploadExcludeFile: .dockerignore
    ssh:
      enabled: false
