---
version: '3'

services:
  nats:
    image: nats:2.10.24-alpine
    command: "--jetstream"
    ports:
    - 4222:4222
    networks:
    - main

  opensearch:
    image: docker.io/opensearchproject/opensearch:2.3.0
    user: 1000:1000
    environment:
    - cluster.name=opensearch-cluster
    - discovery.type=single-node
    - bootstrap.memory_lock=true
    - plugins.security.disabled=true
    - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
    - 9200:9200
    networks:
    - main

  dragonflydb:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.16.0
    ports:
    - 6379:6379
    networks:
    - main

networks:
  main:
