apiVersion: v1
kind: Pod
metadata:
  annotations:
    job.runner.gitlab.com/before_sha: "0000000000000000000000000000000000000000"
    job.runner.gitlab.com/id: "2283"
    job.runner.gitlab.com/name: fdp
    job.runner.gitlab.com/ref: refs/merge-requests/1/head
    job.runner.gitlab.com/sha: 96dfe16923d37c7d4f3ef3b17d0096b0bdd1d0c3
    job.runner.gitlab.com/url: https://ssd-git.p8.japannext.co.jp/ssd/jnx-all/-/jobs/2283
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: ephemeral-storage request
      for container build; ephemeral-storage limit for container build; ephemeral-storage
      request for container helper; ephemeral-storage limit for container helper;
      ephemeral-storage request for init container init-permissions; ephemeral-storage
      limit for init container init-permissions'
    project.runner.gitlab.com/id: "3"
  creationTimestamp: "2025-01-07T06:33:36Z"
  labels:
    pod: runner-t3ifslm-project-3-concurrent-6
  name: runner-t3ifslm-project-3-concurrent-6-9yy08kct
  namespace: jnx-yaala
  resourceVersion: "1262997110"
  uid: 3c4b301f-727f-43db-b380-a8cf9b8d803d
spec:
  activeDeadlineSeconds: 3601
  affinity: {}
  containers:
  - command:
    - sh
    - -c
    - "if [ -x /usr/local/bin/bash ]; then\n\texec /usr/local/bin/bash \nelif [ -x
      /usr/bin/bash ]; then\n\texec /usr/bin/bash \nelif [ -x /bin/bash ]; then\n\texec
      /bin/bash \nelif [ -x /usr/local/bin/sh ]; then\n\texec /usr/local/bin/sh \nelif
      [ -x /usr/bin/sh ]; then\n\texec /usr/bin/sh \nelif [ -x /bin/sh ]; then\n\texec
      /bin/sh \nelif [ -x /busybox/sh ]; then\n\texec /busybox/sh \nelse\n\techo shell
      not found\n\texit 1\nfi\n\n"
    env:
    - name: FF_TEST_FEATURE
      value: "false"
    - name: FF_NETWORK_PER_BUILD
      value: "false"
    - name: FF_USE_LEGACY_KUBERNETES_EXECUTION_STRATEGY
      value: "false"
    - name: FF_USE_DIRECT_DOWNLOAD
      value: "true"
    - name: FF_SKIP_NOOP_BUILD_STAGES
      value: "true"
    - name: FF_USE_FASTZIP
      value: "false"
    - name: FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR
      value: "false"
    - name: FF_ENABLE_BASH_EXIT_CODE_CHECK
      value: "false"
    - name: FF_USE_WINDOWS_LEGACY_PROCESS_STRATEGY
      value: "false"
    - name: FF_USE_NEW_BASH_EVAL_STRATEGY
      value: "false"
    - name: FF_USE_POWERSHELL_PATH_RESOLVER
      value: "false"
    - name: FF_USE_DYNAMIC_TRACE_FORCE_SEND_INTERVAL
      value: "false"
    - name: FF_SCRIPT_SECTIONS
      value: "false"
    - name: FF_ENABLE_JOB_CLEANUP
      value: "false"
    - name: FF_KUBERNETES_HONOR_ENTRYPOINT
      value: "false"
    - name: FF_POSIXLY_CORRECT_ESCAPES
      value: "false"
    - name: FF_RESOLVE_FULL_TLS_CHAIN
      value: "false"
    - name: FF_DISABLE_POWERSHELL_STDIN
      value: "false"
    - name: FF_USE_POD_ACTIVE_DEADLINE_SECONDS
      value: "true"
    - name: FF_USE_ADVANCED_POD_SPEC_CONFIGURATION
      value: "false"
    - name: FF_SET_PERMISSIONS_BEFORE_CLEANUP
      value: "true"
    - name: FF_SECRET_RESOLVING_FAILS_IF_MISSING
      value: "true"
    - name: FF_RETRIEVE_POD_WARNING_EVENTS
      value: "true"
    - name: FF_PRINT_POD_EVENTS
      value: "false"
    - name: FF_USE_GIT_BUNDLE_URIS
      value: "true"
    - name: FF_USE_DUMB_INIT_WITH_KUBERNETES_EXECUTOR
      value: "false"
    - name: FF_USE_INIT_WITH_DOCKER_EXECUTOR
      value: "false"
    - name: FF_LOG_IMAGES_CONFIGURED_FOR_JOB
      value: "false"
    - name: FF_USE_DOCKER_AUTOSCALER_DIAL_STDIO
      value: "true"
    - name: FF_CLEAN_UP_FAILED_CACHE_EXTRACT
      value: "false"
    - name: FF_USE_WINDOWS_JOB_OBJECT
      value: "false"
    - name: FF_TIMESTAMPS
      value: "false"
    - name: FF_DISABLE_AUTOMATIC_TOKEN_ROTATION
      value: "false"
    - name: FF_USE_LEGACY_GCS_CACHE_ADAPTER
      value: "false"
    - name: FF_DISABLE_UMASK_FOR_KUBERNETES_EXECUTOR
      value: "false"
    - name: FF_USE_LEGACY_S3_CACHE_ADAPTER
      value: "false"
    - name: FF_GIT_URLS_WITHOUT_TOKENS
      value: "false"
    - name: FF_WAIT_FOR_POD_TO_BE_REACHABLE
      value: "false"
    - name: CI_JOB_IMAGE
      value: nexus.dc.japannext.co.jp:8442/ssd/rockylinux:8.2024.11.01
    - name: CI_RUNNER_SHORT_TOKEN
      value: t3_ifsLm
    - name: DOCKER_AUTH_CONFIG
      value: '{"auths":{"nexus.dc.japannext.co.jp:8442":{"auth":"c3NkLXlhYWxhOllhYWxhMjAyNDEyMDkK"},"nexus.dc.japannext.co.jp:8083":{"auth":"c3NkLXlhYWxhOllhYWxhMjAyNDEyMDkK"}}}'
    - name: REGISTRY
      value: nexus.dc.japannext.co.jp:8442
    - name: CI_BUILDS_DIR
      value: /builds
    - name: CI_PROJECT_DIR
      value: /builds/ssd/jnx-all
    - name: CI_CONCURRENT_ID
      value: "6"
    - name: CI_CONCURRENT_PROJECT_ID
      value: "6"
    - name: CI_SERVER
      value: "yes"
    - name: CI_JOB_STATUS
      value: running
    - name: CI_JOB_TIMEOUT
      value: "3600"
    - name: CI_SERVER_TLS_CA_FILE
      value: /builds/ssd/jnx-all.tmp/CI_SERVER_TLS_CA_FILE
    - name: CI_PIPELINE_ID
      value: "329"
    - name: CI_PIPELINE_URL
      value: https://ssd-git.p8.japannext.co.jp/ssd/jnx-all/-/pipelines/329
    - name: CI_JOB_ID
      value: "2283"
    - name: CI_JOB_URL
      value: https://ssd-git.p8.japannext.co.jp/ssd/jnx-all/-/jobs/2283
    - name: CI_JOB_STARTED_AT
      value: "2025-01-07T06:33:35Z"
    - name: CI_REGISTRY_USER
      value: gitlab-ci-token
    - name: CI_JOB_NAME
      value: fdp
    - name: CI_JOB_NAME_SLUG
      value: fdp
    - name: CI_JOB_STAGE
      value: build
    - name: CI_NODE_TOTAL
      value: "1"
    - name: CI
      value: "true"
    - name: GITLAB_CI
      value: "true"
    - name: CI_SERVER_FQDN
      value: ssd-git.p8.japannext.co.jp
    - name: CI_SERVER_URL
      value: https://ssd-git.p8.japannext.co.jp
    - name: CI_SERVER_HOST
      value: ssd-git.p8.japannext.co.jp
    - name: CI_SERVER_PORT
      value: "443"
    - name: CI_SERVER_PROTOCOL
      value: https
    - name: CI_SERVER_SHELL_SSH_HOST
      value: ssd-git.p8.japannext.co.jp
    - name: CI_SERVER_SHELL_SSH_PORT
      value: "22"
    - name: CI_SERVER_NAME
      value: GitLab
    - name: CI_SERVER_VERSION
      value: 17.5.1
    - name: CI_SERVER_VERSION_MAJOR
      value: "17"
    - name: CI_SERVER_VERSION_MINOR
      value: "5"
    - name: CI_SERVER_VERSION_PATCH
      value: "1"
    - name: CI_SERVER_REVISION
      value: e8dca573167
    - name: GITLAB_FEATURES
    - name: CI_PROJECT_ID
      value: "3"
    - name: CI_PROJECT_NAME
      value: jnx-all
    - name: CI_PROJECT_TITLE
      value: jnx-all
    - name: CI_PROJECT_DESCRIPTION
    - name: CI_PROJECT_PATH
      value: ssd/jnx-all
    - name: CI_PROJECT_PATH_SLUG
      value: ssd-jnx-all
    - name: CI_PROJECT_NAMESPACE
      value: ssd
    - name: CI_PROJECT_NAMESPACE_ID
      value: "12"
    - name: CI_PROJECT_ROOT_NAMESPACE
      value: ssd
    - name: CI_PROJECT_URL
      value: https://ssd-git.p8.japannext.co.jp/ssd/jnx-all
    - name: CI_PROJECT_VISIBILITY
      value: private
    - name: CI_PROJECT_REPOSITORY_LANGUAGES
      value: c++,c,java,python,typescript
    - name: CI_PROJECT_CLASSIFICATION_LABEL
    - name: CI_DEFAULT_BRANCH
      value: main
    - name: CI_CONFIG_PATH
      value: .gitlab-ci.yml
    - name: CI_PAGES_DOMAIN
      value: pages-ssd.ssd-git.p8.japannext.co.jp
    - name: CI_PAGES_URL
      value: https://ssd.pages-ssd.ssd-git.p8.japannext.co.jp/jnx-all
    - name: CI_REGISTRY
      value: ssd-registry.p8.japannext.co.jp
    - name: CI_API_V4_URL
      value: https://ssd-git.p8.japannext.co.jp/api/v4
    - name: CI_API_GRAPHQL_URL
      value: https://ssd-git.p8.japannext.co.jp/api/graphql
    - name: CI_TEMPLATE_REGISTRY_HOST
      value: registry.gitlab.com
    - name: CI_PIPELINE_IID
      value: "309"
    - name: CI_PIPELINE_SOURCE
      value: parent_pipeline
    - name: CI_PIPELINE_CREATED_AT
      value: "2025-01-07T06:30:06Z"
    - name: CI_PIPELINE_NAME
    - name: CI_COMMIT_SHA
      value: 96dfe16923d37c7d4f3ef3b17d0096b0bdd1d0c3
    - name: CI_COMMIT_SHORT_SHA
      value: 96dfe169
    - name: CI_COMMIT_BEFORE_SHA
      value: "0000000000000000000000000000000000000000"
    - name: CI_COMMIT_REF_NAME
      value: local-dev
    - name: CI_COMMIT_REF_SLUG
      value: local-dev
    - name: CI_COMMIT_MESSAGE
      value: |
        [gitlab] next batch to test gitlab runner
    - name: CI_COMMIT_TITLE
      value: '[gitlab] next batch to test gitlab runner'
    - name: CI_COMMIT_DESCRIPTION
    - name: CI_COMMIT_REF_PROTECTED
      value: "false"
    - name: CI_COMMIT_TIMESTAMP
      value: "2025-01-07T15:28:02+09:00"
    - name: CI_COMMIT_AUTHOR
      value: Migdonio Rodriguez <migdonio.rodriguez@japannext.co.jp>
    - name: CI_MERGE_REQUEST_EVENT_TYPE
      value: detached
    - name: CI_MERGE_REQUEST_SOURCE_BRANCH_SHA
    - name: CI_MERGE_REQUEST_TARGET_BRANCH_SHA
    - name: CI_MERGE_REQUEST_DIFF_ID
      value: "55"
    - name: CI_MERGE_REQUEST_DIFF_BASE_SHA
      value: 67d4ae7c7ca5400c5bfabc432bfe6e64ced696d8
    - name: CI_MERGE_REQUEST_ID
      value: "9"
    - name: CI_MERGE_REQUEST_IID
      value: "1"
    - name: CI_MERGE_REQUEST_REF_PATH
      value: refs/merge-requests/1/head
    - name: CI_MERGE_REQUEST_PROJECT_ID
      value: "3"
    - name: CI_MERGE_REQUEST_PROJECT_PATH
      value: ssd/jnx-all
    - name: CI_MERGE_REQUEST_PROJECT_URL
      value: https://ssd-git.p8.japannext.co.jp/ssd/jnx-all
    - name: CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      value: main
    - name: CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED
      value: "false"
    - name: CI_MERGE_REQUEST_TITLE
      value: Local dev
    - name: CI_MERGE_REQUEST_DESCRIPTION
    - name: CI_MERGE_REQUEST_DESCRIPTION_IS_TRUNCATED
      value: "false"
    - name: CI_MERGE_REQUEST_ASSIGNEES
      value: migdonio.rodriguez
    - name: CI_MERGE_REQUEST_SQUASH_ON_MERGE
      value: "false"
    - name: CI_MERGE_REQUEST_SOURCE_PROJECT_ID
      value: "3"
    - name: CI_MERGE_REQUEST_SOURCE_PROJECT_PATH
      value: ssd/jnx-all
    - name: CI_MERGE_REQUEST_SOURCE_PROJECT_URL
      value: https://ssd-git.p8.japannext.co.jp/ssd/jnx-all
    - name: CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
      value: local-dev
    - name: CI_MERGE_REQUEST_SOURCE_BRANCH_PROTECTED
      value: "false"
    - name: CI_OPEN_MERGE_REQUESTS
      value: ssd/jnx-all!1
    - name: CI_RUNNER_ID
      value: "52"
    - name: CI_RUNNER_DESCRIPTION
      value: ssd-git-gitlab-runner-75757f85ff-g7c88
    - name: CI_RUNNER_TAGS
      value: '["k8s", "p8", "d8", "k8s-rhel", "k8s-alpine", "docker", "light", "minerva",
        "aeron", "mercury", "x-stream", "heavy", "centos", "centos7", "mmi1runner01",
        "mmi1runner02", "rocky", "rocky8"]'
    - name: MARKET_TYPE
      value: fdp
    - name: GITLAB_USER_ID
      value: "10"
    - name: GITLAB_USER_EMAIL
      value: migdonio.rodriguez@japannext.co.jp
    - name: GITLAB_USER_LOGIN
      value: migdonio.rodriguez
    - name: GITLAB_USER_NAME
      value: Migdonio Rodriguez
    - name: CI_DISPOSABLE_ENVIRONMENT
      value: "true"
    - name: CI_RUNNER_VERSION
      value: 17.5.4
    - name: CI_RUNNER_REVISION
      value: d8d88d9e
    - name: CI_RUNNER_EXECUTABLE_ARCH
      value: linux/amd64
    - name: RUNNER_TEMP_PROJECT_DIR
      value: /builds/ssd/jnx-all.tmp
    image: nexus.dc.japannext.co.jp:8442/ssd/rockylinux:8.2024.11.01
    imagePullPolicy: IfNotPresent
    name: build
    resources:
      limits:
        ephemeral-storage: 1Gi
      requests:
        ephemeral-storage: 100Mi
    securityContext:
      capabilities:
        drop:
        - NET_RAW
      privileged: true
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /scripts-3-2283
      name: scripts
    - mountPath: /logs-3-2283
      name: logs
    - mountPath: /home/gitlab-runner/.gitlab-runner/certs/
      name: gitlab-dc-jnx-cert
    - mountPath: /cache
      name: ssd-git-gitlab-runner-jnx-cache-pvc
    - mountPath: /data_mount
      name: ssd-git-gitlab-runner-jnx-artifacts-pvc
    - mountPath: /coverage
      name: ssd-git-gitlab-runner-jnx-coverage-pvc
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /builds
      name: repo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lmxvx
      readOnly: true
  - command:
    - sh
    - -c
    - "if [ -x /usr/local/bin/bash ]; then\n\texec /usr/local/bin/bash \nelif [ -x
      /usr/bin/bash ]; then\n\texec /usr/bin/bash \nelif [ -x /bin/bash ]; then\n\texec
      /bin/bash \nelif [ -x /usr/local/bin/sh ]; then\n\texec /usr/local/bin/sh \nelif
      [ -x /usr/bin/sh ]; then\n\texec /usr/bin/sh \nelif [ -x /bin/sh ]; then\n\texec
      /bin/sh \nelif [ -x /busybox/sh ]; then\n\texec /busybox/sh \nelse\n\techo shell
      not found\n\texit 1\nfi\n\n"
    image: nexus.dc.japannext.co.jp:8442/gitlab/gitlab-runner-helper:x86_64-v15.11.1
    imagePullPolicy: IfNotPresent
    name: helper
    resources:
      limits:
        ephemeral-storage: 1Gi
      requests:
        ephemeral-storage: 100Mi
    securityContext:
      capabilities:
        drop:
        - NET_RAW
      privileged: true
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /scripts-3-2283
      name: scripts
    - mountPath: /logs-3-2283
      name: logs
    - mountPath: /home/gitlab-runner/.gitlab-runner/certs/
      name: gitlab-dc-jnx-cert
    - mountPath: /cache
      name: ssd-git-gitlab-runner-jnx-cache-pvc
    - mountPath: /data_mount
      name: ssd-git-gitlab-runner-jnx-artifacts-pvc
    - mountPath: /coverage
      name: ssd-git-gitlab-runner-jnx-coverage-pvc
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /builds
      name: repo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lmxvx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: runner-t3ifslm-project-3-concurrent-6-fjhuild5
  initContainers:
  - command:
    - sh
    - -c
    - touch /logs-3-2283/output.log && (chmod 777 /logs-3-2283/output.log || exit
      0)
    image: nexus.dc.japannext.co.jp:8442/gitlab/gitlab-runner-helper:x86_64-v15.11.1
    imagePullPolicy: IfNotPresent
    name: init-permissions
    resources:
      limits:
        ephemeral-storage: 1Gi
      requests:
        ephemeral-storage: 100Mi
    securityContext:
      capabilities:
        drop:
        - NET_RAW
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /scripts-3-2283
      name: scripts
    - mountPath: /logs-3-2283
      name: logs
    - mountPath: /home/gitlab-runner/.gitlab-runner/certs/
      name: gitlab-dc-jnx-cert
    - mountPath: /cache
      name: ssd-git-gitlab-runner-jnx-cache-pvc
    - mountPath: /data_mount
      name: ssd-git-gitlab-runner-jnx-artifacts-pvc
    - mountPath: /coverage
      name: ssd-git-gitlab-runner-jnx-coverage-pvc
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /builds
      name: repo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-lmxvx
      readOnly: true
  nodeName: dmi1kubectl01
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: gitlab-dc-jnx-cert
    secret:
      defaultMode: 420
      secretName: gitlab-dc-jnx-cert
  - name: ssd-git-gitlab-runner-jnx-cache-pvc
    persistentVolumeClaim:
      claimName: ssd-git-gitlab-runner-jnx-cache-pvc
  - name: ssd-git-gitlab-runner-jnx-artifacts-pvc
    persistentVolumeClaim:
      claimName: ssd-git-gitlab-runner-jnx-artifacts-pvc
  - name: ssd-git-gitlab-runner-jnx-coverage-pvc
    persistentVolumeClaim:
      claimName: ssd-git-gitlab-runner-jnx-coverage-pvc
  - emptyDir:
      medium: Memory
    name: dshm
  - emptyDir: {}
    name: repo
  - emptyDir: {}
    name: scripts
  - emptyDir: {}
    name: logs
  - name: kube-api-access-lmxvx
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-01-07T06:34:24Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-01-07T06:34:44Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-01-07T06:34:44Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-01-07T06:33:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://361924ac199faf2187a7b6372550aa141b5fe0465c2bd86c2218355a9efb1784
    image: nexus.dc.japannext.co.jp:8442/ssd/rockylinux:8.2024.11.01
    imageID: nexus.dc.japannext.co.jp:8442/ssd/rockylinux@sha256:4f1bd00f64ba634371f93ff10c1682c046a7d87901785667d944662b109d0fd6
    lastState: {}
    name: build
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-01-07T06:34:32Z"
  - containerID: containerd://75fd2d37e5ac7a59cc8534c33338a573fa167240da6d4f442c2700f86fafbad1
    image: nexus.dc.japannext.co.jp:8442/gitlab/gitlab-runner-helper:x86_64-v15.11.1
    imageID: nexus.dc.japannext.co.jp:8442/gitlab/gitlab-runner-helper@sha256:ce6a6505958b93206b7fd96458843a8fbfadd1be3b50c099a43eabdb18e8fb02
    lastState: {}
    name: helper
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-01-07T06:34:43Z"
  hostIP: 10.68.112.21
  initContainerStatuses:
  - containerID: containerd://b676a744d06297600d6281f99eeeb77ea13286f03cd5d766344c13e7150184d1
    image: nexus.dc.japannext.co.jp:8442/gitlab/gitlab-runner-helper:x86_64-v15.11.1
    imageID: nexus.dc.japannext.co.jp:8442/gitlab/gitlab-runner-helper@sha256:ce6a6505958b93206b7fd96458843a8fbfadd1be3b50c099a43eabdb18e8fb02
    lastState: {}
    name: init-permissions
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://b676a744d06297600d6281f99eeeb77ea13286f03cd5d766344c13e7150184d1
        exitCode: 0
        finishedAt: "2025-01-07T06:34:09Z"
        reason: Completed
        startedAt: "2025-01-07T06:34:07Z"
  phase: Running
  podIP: 172.16.3.93
  podIPs:
  - ip: 172.16.3.93
  qosClass: BestEffort
  startTime: "2025-01-07T06:33:36Z"
