---
version: '3'

dotenv: ['.env.local']

vars:
  VERSION: 2.0.0
  COMMIT:
    sh: git rev-parse --short HEAD

includes:
  image:
    taskfile: ./tasks/image.yaml
  chart:
    taskfile: ./charts/snooze/Taskfile.yaml
    dir: ./charts/snooze

tasks:

  build:
    cmds:
    - go fmt .
    - go vet .
    - go build -o /dev/null .

  test:
    cmds:
    - go test ./...

  develop:
    cmds:
    - task: build
    - task: image:develop
    - task: chart:develop
    - task: sync

  samples:
    cmds:
    - curl https://snooze2.d8.japannext.co.jp/api/sample -X POST

  cleanup:
    cmds:
    - kubectl exec -it snooze-opensearch-masters-0 -- curl -k -u admin:admin https://localhost:9200/_data_stream/v2-logs -X DELETE
    - kubectl exec -it snooze-opensearch-masters-0 -- curl -k -u admin:admin https://localhost:9200/_index_template/v2-logs -X DELETE
    - kubectl exec -it snooze-opensearch-masters-0 -- curl -k -u admin:admin https://localhost:9200/_data_stream/v2-notifications -X DELETE
    - kubectl exec -it snooze-opensearch-masters-0 -- curl -k -u admin:admin https://localhost:9200/_index_template/v2-notifications -X DELETE
    - kubectl exec -it snooze-opensearch-masters-0 -- curl -k -u admin:admin https://localhost:9200/_index_template/v2-alerts -X DELETE

  sync:
    cmds:
    # - docker inspect --format='{{"{{"}}index .RepoDigests 0{{"}}"}}' nexus.dc.japannext.co.jp:8083/unix/kubernetes/snooze:develop | cut -d@ -f2 > .digest
    - helmfile -f .helmfile.yaml.gotmpl sync
    - kubectl rollout restart deploy/snooze-{syslog,process,apiserver,mail,alertmanager}
