---
version: '3'

dotenv: ['.env.local']

vars:
  VERSION: 2.0.0
  COMMIT:
    sh: git rev-parse --short HEAD

includes:
  image:
    taskfile: ./tasks/image.yaml
  chart:
    taskfile: ./charts/snooze/Taskfile.yaml
    dir: ./charts/snooze

tasks:
  build:
    cmds:
    - go fmt ./...
    - go vet ./...
    - go build ./...
  develop:
    cmds:
    - task: images:develop
    - task: chart:develop
  images:develop:
    cmds:
    - task: image:develop
      vars: {NAME: snooze-apiserver}
    - task: image:develop
      vars: {NAME: snooze-processor}
    - task: image:develop
      vars: {NAME: snooze-otel}

  test:
    cmds:
    - go test ./...
