---
version: '3'

dotenv:
- .env.local

vars:
  NAME: snooze-server
  VERSION:
    sh: uv version --short
  REPO: ghcr.io/japannext

includes:
  web:
    taskfile: ./web/Taskfile.yaml
    dir: ./web
  chart:
    taskfile: ./packaging/helm/Taskfile.yaml
    dir: ./packaging/helm
  syslog:
    taskfile: ./components/syslog/Taskfile.yaml
    dir: ./components/syslog
  googlechat:
    taskfile: ./components/googlechat/Taskfile.yaml
    dir: ./components/googlechat
  snmptrap:
    taskfile: ./components/snmptrap/Taskfile.yaml
    dir: ./components/snmptrap

tasks:
  py:lint:
    cmds:
    - ruff check

  py:test:
    desc: Run pytest
    cmds:
    - PYTHONPATH=src uv run pytest

  py:build:
    desc: Build the python snooze-server
    cmds:
    - uv build

  cacert:
    desc: Setup the CA bundle from the build environment
    cmds:
    - mkdir -p .ca-bundle
    - cp /etc/pki/ca-trust/source/anchors/* .ca-bundle/
    status:
    - find .ca-bundle -name '*.crt'

  docker:develop:
    desc: Build the docker image
    deps:
    - cacert
    cmds:
    - docker build -f packaging/Dockerfile . -t {{ .LOCAL_REPO }}/{{ .NAME }}:latest --no-cache
    - docker push {{ .LOCAL_REPO }}/{{ .NAME  }}:latest
    preconditions:
    - sh: test -n "{{ .LOCAL_REPO }}"
      msg: "You need to define LOCAL_REPO=... in .env.local!"
    - sh: docker login "{{ .LOCAL_REPO }}" --get-login
      msg: "You need to login to docker with `docker login {{ .LOCAL_REPO }}`"

  docker:release:
    desc: Release to GHCR
    deps:
    - cacert
    cmds:
    - docker build -f packaging/Dockerfile . -t {{ .REPO }}/{{ .NAME }}:{{ .VERSION }}
    - docker push {{ .REPO }}/{{ .NAME  }}:{{ .VERSION }}
    preconditions:
    - sh: docker login "{{ .REPO }}" --get-login
      msg: "You need to login to docker with `docker login {{ .REPO }}`"
