---
version: '3'

dotenv: ['.env.local']

vars:
  VERSION: 2.0.0
  COMMIT:
    sh: git rev-parse --short HEAD

includes:
  image:
    taskfile: ./tasks/image.yaml
  chart:
    taskfile: ./charts/snooze/Taskfile.yaml
    dir: ./charts/snooze

tasks:

  build:
    cmds:
    - go fmt ./...
    - go vet ./...
    - go build ./...

  test:
    cmds:
    - go test ./...

  develop:
    cmds:
    - task: build
    - task: image:develop
    - task: chart:develop
    - task: sync

  sync:
    cmds:
    - helmfile -f .helmfile.yaml sync
