---
version: '3'

vars:
  REPO: jnx-repo-upload
  NAME:
    sh: "grep -oP '^name: \\K.*' Chart.yaml"
  VERSION:
    sh: "grep -oP '^version: \\K.*' Chart.yaml"

tasks:
  lint:
    desc: Lint the helm chart
    cmds:
    - helm lint

  develop:
    desc: Upload a dev version of the chart for testing
    cmds:
    - mkdir -p .charts
    - helm package . --version 0.0.0-dev -d .charts/
    - helm cm-push .charts/{{ .NAME }}-0.0.0-dev.tgz {{ .REPO }}
    preconditions:
    - sh: "helm repo list | awk '{print $1}' | grep -w '{{ .REPO }}'"
      msg: "You need to setup your helm repo: https://gitlab.dc.japannext.co.jp/kubernetes/charts/repo#how-to-upload"

  release:
    desc: Release the finished helm chart, versionned
    cmds:
    - mkdir -p .charts
    - helm package . --version {{ .VERSION }} -d .charts/
    - helm cm-push .charts/{{ .NAME }}-{{ .VERSION }}.tgz {{ .REPO }}
    preconditions:
    - sh: "helm repo list | awk '{print $1}' | grep -w '{{ .REPO }}'"
      msg: "You need to setup your helm repo: https://gitlab.dc.japannext.co.jp/kubernetes/charts/repo#how-to-upload"
    status:
    - helm repo update {{ .REPO }} && helm show chart {{ .REPO }}/{{ .NAME }} --version {{ .VERSION }}
