---

image:
  repo: ghcr.io/japannext/snooze
  tag: ""
  pullPolicy: IfNotPresent

pipeline:
  transform_rules: []
  silence_rules: []
  grouping_rules:
  - name: by-service
    if: '(has labels[service.name]) and (has labels[environment])'
    group_by: ['labels[service.name]', 'labels[environment]']
  - name: by-k8s-deploy
    if: '(has labels[k8s.deployment.name]) and (has labels[k8s.namespace.name]) and (has labels[k8s.cluster.name])'
    group_by: ['labels[k8s.deployment.name]', 'labels[k8s.namespace.name]', 'labels[k8s.cluster.name]']
  - name: by-k8s-sts
    if: '(has labels[k8s.statefulset.name]) and (has labels[k8s.namespace.name]) and (has labels[k8s.cluster.name])'
    group_by: ['labels[k8s.statefulset.name]', 'labels[k8s.namespace.name]', 'labels[k8s.cluster.name]']
  - name: by-syslog-host
    if: 'has attributes[appname] and attributes[hostname]'
    group_by: ['attributes[appname]', 'attributes[hostname]']
  ratelimit:
    burst: 50
    period: 1m
    cooldown: 5m
  notification_rules:
  - if: 'attributes[owner] == "unix"'
    channels: ['googlechat:unix']
  default_notification_channels:
  - 'googlechat:unix'
  - 'googlechat:monitoring'
  - 'patlite:purple'

process:
  replicaCount: 2

api:
  replicaCount: 2

opensearch:
  enabled: true
  replicas: 3
  maxUnavailable: 1
  opensearchJavaOpts: '-Xmx2g -Xms2g'
  extraEnvs:
  - name: POD_NAME
    valueFrom: {fieldRef: {fieldPath: metadata.name}}
  - name: node.name
    value: ${POD_NAME}.opensearch-headless
  config:
    opensearch.yml: |-
      cluster.name: opensearch-cluster
      network.host: 0.0.0.0
      node.processors: 8
      plugins:
        security:
          ssl:
            transport:
              pemcert_filepath: tls/tls.crt
              pemkey_filepath: tls/tls.key
              pemtrustedcas_filepath: tls/ca.crt
              enforce_hostname_verification: false
              resolve_hostname: false
            http:
              enabled: true
              pemcert_filepath: tls/tls.crt
              pemkey_filepath: tls/tls.key
              pemtrustedcas_filepath: tls/ca.crt
          allow_unsafe_democertificates: true
          allow_default_init_securityindex: true
  sysctl:
    image:
      repo: busybox
      tag: latest
      pullPolicy: IfNotPresent

rabbitmq:
  enabled: true
  replicaCount: 3
  storageClassName: openebs-lvm-sysvg
  storageSize: 20Gi

ingress:
  enabled: false
  className: nginx
  host: ""
  dashboardHost: ""
  domain: ""
  certManager:
    enabled: false
    issuerKind: Issuer
    issuerName: default
