---
version: '3'

tasks:
  develop:
    cmds:
    - docker build . --target={{ .NAME }}
      -t ${LOCAL_REPO}/{{ .NAME }}
      --build-arg VERSION={{ .VERSION }}-develop
      --build-arg COMMIT={{ .COMMIT }}
    - docker push ${LOCAL_REPO}/{{ .NAME }}:develop
    preconditions:
    - sh: '[[ -n "${LOCAL_REPO}" ]]'
      msg: "You need to set LOCAL_REPO=myrepo.example.com:8080 in '.env.local' to use develop tasks"
    - sh: docker login ${LOCAL_REPO} --get-login
      msg: "You need to login to docker with `docker login ${LOCAL_REPO}`"
