---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-googlechat"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: snooze
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: googlechat
    app.kubernetes.io/part-of: "{{ .Values.partOf }}"
spec:
  replicas: {{ .Values.googlechat.replicaCount }}
  revisionHistoryLimit: {{ .Values.googlechat.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: snooze
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: googlechat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snooze
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: googlechat
        app.kubernetes.io/part-of: "{{ .Values.partOf }}"
    spec:
      containers:
      - name: snooze-googlechat
        image: "{{- include "snooze.image" . | trim }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args:
        - googlechat
        ports:
        - name: rest-api
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        {{- include "snooze.nats.env" . | nindent 8 }}
        {{- if .Values.cacertConfigMap }}
        - name: SNOOZE_CACERT
          value: "/cacert/ca.crt"
        - name: GOOGLECHAT_SA_PATH
          value: /sa/sa.json
        {{- end }}
        envFrom:
        - configMapRef:
            name: "{{ .Release.Name }}-common"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: sa
          mountPath: /sa
        {{- if .Values.cacertConfigMap }}
        - name: cacert
          mountPath: /cacert
        {{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: config
        configMap:
          name: "{{ .Release.Name }}-googlechat-profiles"
      - name: sa
        secret:
          secretName: "{{ .Values.googlechat.saSecretName }}"
      {{- with .Values.cacertConfigMap }}
      - name: cacert
        configMap:
          name: "{{ . }}"
      {{- end }}
