{{- if .Values.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "{{ .Release.Name }}-activecheck"
  namespace: "{{ .Release.Namespace }}"
  {{- with .Values.podMonitor.extraLabels }}
  labels:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  podMetricsEndpoints:
  - path: /probe/snooze-syslog
    port: http
    scheme: http
    interval: 30s
    scrapeTimeout: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: snooze
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: activecheck
{{- end }}
