---
version: '3'

vars:
  CHART_NAME:
    sh: "grep -oP '^name: \\K.*' Chart.yaml"
  CHART_VERSION:
    sh: "grep -oP '^version: \\K.*' Chart.yaml"
  OCI_REGISTRY: ghcr.io/japannext/helm-charts

tasks:
  lint:
    desc: Lint the helm chart
    deps: [docs, schema]
    cmds:
    - helm lint

  docs:
    cmds:
    - helm-docs

  schema:
    cmds:
    - helm-schema -k required

  develop:
    desc: Use helmfile to sync the chart to a local k8s environment
    deps: [lint]
    cmds:
    - helmfile -f .helmfile.yaml sync
    preconditions:
    - sh: test -f .helmfile.yaml
      msg: "You need to define a .helmfile.yaml in helmfile format that will be synced"

  release:
    desc: Release the finished helm chart, versionned
    deps: [lint]
    cmds:
    - mkdir -p .charts
    - helm package . --version {{ .CHART_VERSION }} -d .charts/
    - helm push .charts/{{ .CHART_NAME }}-{{ .CHART_VERSION }}.tgz oci://{{ .OCI_REGISTRY }}
