---
server:
  # -- Number of replicas of snooze-server to run
  replicaCount: 3
  image:
    # -- The image to use for snooze-server
    repository: ghcr.io/japannext/snooze-server
    # -- A tag override for snooze-server
    tag: ""
    # -- Image pull policy of snooze-server
    pullPolicy: IfNotPresent

  config:
    defaultAuthBackend: ldap

  ldap:
    # -- Enable LDAP authentication configuration
    enabled: false
    # -- The LDAP host to contact
    host: ""
    port: 636
    baseDN: ""
    # -- The bindDN to use for LDAP authentication
    bindDN: ""
    # -- Name of the secret containing the bind password
    bindPasswordExistingSecretName: ""
    # -- The key in the secret containing the bind password
    bindPasswordExistingSecretKey: "password"
    # -- The LDAP user filter for LDAP authentication
    userFilter: '(sAMAccountName=%s)'
    displayNameAttribute: 'cn'
    emailAttribute: 'mail'
    groupDN: ''
    memberAttribute: 'memberOf'

ingress:
  # -- Ingress class name
  className: nginx
  # -- The host to use for ingress
  host: ""
  certManager:
    # -- Whether cert-manager will be used for ingress certificate
    enabled: false
    # -- The kind of cert-manager issuer
    issuerKind: ClusterIssuer
    # -- The name of the cert-manager issuer
    issuerName: ""

syslog:
  # -- When enabled, deploy snooze-syslog inputs
  enabled: true
  # -- Number of snooze-syslog replicas
  replicaCount: 2
  image:
    # -- The image to use for snooze-syslog
    repository: ghcr.io/japannext/snooze-syslog
    # -- A tag override for snooze-syslog
    tag: ""
    # -- Image pull policy of snooze-syslog
    pullPolicy: IfNotPresent
  workers: 4

snmptrap:
  # -- When enabled, deploy snooze-snmptrap inputs
  enabled: true
  # -- Number of snooze-snmptrap replicas
  replicaCount: 2
  image:
    # -- The image to use for snooze-snmptrap
    repository: ghcr.io/japannext/snooze-snmptrap
    # -- A tag override for snooze-snmptrap
    tag: ""
    # -- Image pull policy of snooze-snmptrap
    pullPolicy: IfNotPresent
  sendWorkers: 4

googlechat:
  # -- When enabled, deploy snooze-syslog notification plugin
  enabled: false
  # Number of snooze-googlechat replicas
  replicaCount: 2
  image:
    # -- The image to use for snooze-googlechat
    repository: ghcr.io/japannext/snooze-googlechat
    # -- A tag override for snooze-googlechat
    tag: ""
    # -- Image pull policy of snooze-googlechat
    pullPolicy: IfNotPresent
  botName: "Snooze"
  subscriptionName: ""
  existingSaSecretName: ""
  httpProxy: ""
  httpsProxy: ""
  noProxy: ""

mongodb:
  storageClassName: ""
