---
apiVersion: scylla.scylladb.com/v1
kind: ScyllaCluster
metadata:
  name: "{{ .Release.Name }}-scylladb"
  namespace: "{{ .Release.Namespace }}"
spec:
  version: 2.3.1
  repository: scylladb/scylla
  cpuset: false
  # automaticOrphanatedNodeCleanup: true
  repairs:
  - name: 'daily repair'
    intensity: '2'
    interval: '1d'
    dc: ['cc1']
  datacenter:
    name: cc1
    racks:
    - name: kubernetes
      members: 3
      storage:
        capacity: 50G
        storageClassName: "{{ .Values.storageClass }}"
      resources:
        requests:
          cpu: 1
          memory: 8Gi
        limits:
          cpu: 8
          memory: 32Gi
