---
apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: "{{ .Release.Name }}-mongodb-credentials"
spec:
  fields:
  - encoding: hex
    fieldName: password
    length: "64"
