---
api:
    type: falcon
process_plugins:
    # Plugins with process (order matters)
    - rule
    - snooze
    - notification
database:
    type: mongo
    host: localhost
    port: 27017
stats: false
