---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-mail"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: snooze
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: mail
    app.kubernetes.io/part-of: "{{ .Values.partOf }}"
spec:
  replicas: {{ .Values.mail.replicas }}
  revisionHistoryLimit: {{ .Values.mail.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: snooze
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: mail
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snooze
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: mail
        app.kubernetes.io/part-of: "{{ .Values.partOf }}"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- if .Values.mail.podAnnotations }}
        {{- toYaml .Values.mail.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: snooze-mail
        image: "{{- include "snooze.image" . | trim }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args:
        - mail
        ports:
        - name: rest-api
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        {{- include "snooze.nats.env" . | nindent 8 }}
        - name: SMTP_SERVER
          value: "{{ .Values.mail.config.server }}"
        - name: SMTP_PORT
          value: "{{ .Values.mail.config.port }}"
        - name: SMTP_DEFAULT_SENDER
          value: "{{ .Values.mail.config.defaultSender }}"
        {{- if .Values.cacertConfigMap }}
        - name: SNOOZE_CACERT
          value: "/cacert/ca.crt"
        {{- end }}
        envFrom:
        - configMapRef:
            name: "{{ .Release.Name }}-common"
        volumeMounts:
        - name: config
          mountPath: /config
        {{- if .Values.cacertConfigMap }}
        - name: cacert
          mountPath: /cacert
        {{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      volumes:
      - name: config
        configMap:
          name: "{{ .Release.Name }}-mail-profiles"
      {{- with .Values.cacertConfigMap }}
      - name: cacert
        configMap:
          name: "{{ . }}"
      {{- end }}
