---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-alertmanager"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: snooze
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: alertmanager
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    appProtocol: http
    targetPort: http
  selector:
    app.kubernetes.io/name: snooze
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: alertmanager
