---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-syslog"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: snooze
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: syslog
    app.kubernetes.io/part-of: "{{ .Values.partOf }}"
spec:
  replicas: {{ .Values.syslog.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: snooze
      app.kubernetes.io/instance: "{{ .Release.Name }}"
      app.kubernetes.io/component: syslog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snooze
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/component: syslog
        app.kubernetes.io/part-of: "{{ .Values.partOf }}"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: snooze-syslog
        image: "{{- include "snooze.image" . | trim }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        args:
        - syslog
        ports:
        - name: syslog-udp
          containerPort: 1514
          protocol: UDP
        - name: syslog-tcp
          containerPort: 1514
          protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        {{- include "snooze.nats.env" . | nindent 8 }}
        - name: SYSLOG_INSTANCE_NAME
          value: "{{ .Values.syslog.instanceName }}"
        envFrom:
        - configMapRef:
            name: "{{ .Release.Name }}-common"
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
