---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-syslog"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: snooze-syslog
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: syslog
    app.kubernetes.io/part-of: "{{ .Release.Name }}"
spec:
  type: LoadBalancer
  ports:
  - port: 514
    protocol: TCP
    targetPort: syslog-tcp
    name: syslog-tcp
  - port: 514
    protocol: UDP
    targetPort: syslog-udp
    name: syslog-udp
  selector:
    app.kubernetes.io/name: snooze-syslog
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  sessionAffinity: None
