# vim: ts=2:sts=2:sw=2
---
env:
  browser: true
  es2021: true
  vue/setup-compiler-macros: true
parser: 'vue-eslint-parser'
parserOptions:
  parser:
    js: "espree"
    ts: '@typescript-eslint/parser'
    <template>: "espree"
  sourceType: module
plugins:
  - vue
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - plugin:@typescript-eslint/recommended
rules:
  no-unused-vars: warn
  vue/script-setup-uses-vars: 1
  vue/max-attributes-per-line:
    - error
    - singleline:
        max: 3
      multiline:
        max: 20
  vue/singleline-html-element-content-newline: 'off'
  vue/require-explicit-emits: 'off'
