---
version: '3'

dotenv:
- .env.local

vars:
  NAME: snooze-syslog
  VERSION:
    sh: uv version --short
  REPO: ghcr.io/japannext

tasks:
  py:lint:
    cmds:
    - ruff check

  py:build:
    desc: Build the python package snooze-syslog
    cmds:
    - uv build

  cacert:
    desc: Setup the CA bundle from the build environment
    cmds:
    - mkdir -p .ca-bundle
    - cp /etc/pki/ca-trust/source/anchors/* .ca-bundle/
    status:
    - find .ca-bundle -name '*.crt'

  docker:develop:
    desc: Build the docker image and upload it to a local registry
    deps:
    - cacert
    cmds:
    - docker build . -t {{ .LOCAL_REPO }}/{{ .NAME }}:develop -v ${PWD}/../client:/client 
    - docker push {{ .LOCAL_REPO }}/{{ .NAME  }}:develop
    preconditions:
    - sh: test -n "{{ .LOCAL_REPO }}"
      msg: "You need to define LOCAL_REPO=... in .env.local!"
    - sh: docker login "{{ .LOCAL_REPO }}" --get-login
      msg: "You need to login to docker with `docker login {{ .LOCAL_REPO }}`"

  docker:release:
    desc: Release to GHCR
    deps:
    - cacert
    cmds:
    - docker build . -t {{ .REPO }}/{{ .NAME }}:{{ .VERSION }}
    - docker push {{ .REPO }}/{{ .NAME  }}:{{ .VERSION }}
    preconditions:
    - sh: docker login "{{ .REPO }}" --get-login
      msg: "You need to login to docker with `docker login {{ .REPO }}`"
