---
tabs:
    -
        title: 'Environments'
fields:
    -
        label: Name
        key: name
        sortable: true
        tdStyle: {width: '20%'}
        tdClass: ['align-middle']
    -
        key: filter
        sortable: false
        tdStyle: {width: '50%'}
        tdClass: ['align-middle']
        type: array
    -
        key: color
        sortable: false
        tdStyle: {width: '70px'}
        tdClass: ['align-middle']
        type: array
    -
        label: Comment
        key: comment
        tdStyle: {width: '30%'}
        tdClass: ['align-middle']
        type: array
orderby: tree_order
isascending: true
form:
    name:
        display_name: Name
        component: String
        description: Name of the environment
        required: true
    filter:
        display_name: Filter
        component: Condition
        description: Search filter used to define this environment
    color:
        display_name: Color
        component: ColorSwatches
        description: Color customization
    comment:
        display_name: Comment
        component: Text
