# vim:set ts=2 sw=2 sts=2 et:
---
name: Snooze-server testing

on:
  pull_request:
    branches: [master]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out git repository
        uses: actions/checkout@v2

      - name: Setup python environment
        uses: .github/actions/python-poetry

      - name: Running Pytest
        run: poetry run pytest
