name: Snooze-server testing

on:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python3-dev
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        id: install-deps
        run: |
          python -m pip install --upgrade pip
          pip install \
            pytest \
            pytest-data \
            pytest-mongodb \
            pytest-spec \
            pytest-timeout \
            freezegun
          pip install -r requirements.txt
          pip install .
      - name: Running Pytest
        id: pytest
        run: |
          pytest
