# vim:set softtabstop=2 shiftwidth=2 tabstop=2 expandtab:
---
name: Snooze-server testing

on:
  pull_request:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    if: ${{ false }} # Disabled for now
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Install Poetry
        run: python -m pip install 'poetry>=1.2.0a2'

      - name: Cache Poetry
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: "{{ runner.os }}-poetry-dev-{{ hashFiles('**/poetry.lock') }}"

      - name: Install dependencies
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: poetry install --only lint

      - name: Running Pylint
        run: poetry run pylint snooze/

  tests:
    # needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Install Poetry
        run: python -m pip install 'poetry>=1.2.0a2'

      - name: Cache Poetry
        uses: actions/cache@v1
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: "{{ runner.os }}-poetry-test-{{ hashFiles('**/poetry.lock') }}"

      - name: Install dependencies
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: poetry install --only default --only test

      - name: Running Pytest
        run: poetry run pytest

