---
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - '@vue/typescript/recommended'
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 2021
  sourceType: module
plugins:
  - vue
rules:
  vue/max-attributes-per-line:
    - error
    - singleline: {max: 4}
      multiline: {max: 1}
  vue/singleline-html-element-content-newline: 'off'
  vue/html-self-closing: 'off'
